spring.application.name=notification-service
server.port=8084
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kyvy.2004@gmail.com
spring.mail.password=kvwbfvwwvvdoirol
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.kafka.consumer.group-id=notification-group
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.preferIpAddress=true

# Kafka Topics
kafka.email-register-topic=email-register-topic
kafka.forgot-password-topic=forgot-password-topic
kafka.order-notification-topic=order-notification-topic

# MỚI THÊM CHO GIÁM SÁT
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always