server {
  listen 80;
  server_name localhost;

  # Chỉ định thư mục gốc chứa file build của Angular
  root /usr/share/nginx/html;
  index index.html index.htm;

  # Quan trọng: Cấu hình cho Single Page Application (SPA)
  # Bất kỳ đường dẫn nào không khớp (ví dụ: /login, /profile)
  # sẽ được điều hướng về /index.html để Angular xử lý.
  location / {
    try_files $uri $uri/ /index.html;
  }
}