networks:
  cnpm-network:
    driver: bridge
services:
  # --- INFRASTRUCTURE ---
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - cnpm-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - cnpm-network
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - cnpm-network
  # --- DISCOVERY SERVER ---
  eureka-service:
    image: tcwiuy/eureka-service:latest
    ports:
      - "8761:8761"
    networks:
      - cnpm-network
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

  # --- API GATEWAY ---
  api-gateway:
    image: tcwiuy/api-gateway:latest
    ports:
      - "9000:9000"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
    networks:
      - cnpm-network
    depends_on:
      - redis # Thêm dòng này
      - eureka-service

  # --- MICROSERVICES ---
  user-service:
    ports:
      - "8081:8081"
    image: tcwiuy/user-service:latest
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/user_db
      - SPRING_DATASOURCE_USERNAME=kyvy
      - SPRING_DATASOURCE_PASSWORD=2407
      - APP_BASE_URL=http://api-gateway:9000
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
      - EUREKA_INSTANCE_HOSTNAME=user-service
    networks:
      - cnpm-network
    depends_on:
      - mysql
      - eureka-service
    volumes:
      - ./user-service/src/main/resources/uploads:/app/uploads

  restaurant-service:
    ports:
      - "8082:8082"
    image: tcwiuy/restaurant-service:latest
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
      - APP_BASE_URL=http://api-gateway:9000
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/restaurant_db
      - SPRING_DATASOURCE_USERNAME=kyvy
      - SPRING_DATASOURCE_PASSWORD=2407
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
      - EUREKA_INSTANCE_HOSTNAME=restaurant-service
    networks:
      - cnpm-network
    depends_on:
      - mysql
      - eureka-service
    volumes:
      - ./restaurant-service/src/main/resources/uploads:/app/uploads

  order-service:
    ports:
      - "8083:8083"
    image: tcwiuy/order-service:latest
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/order_db
      - SPRING_DATASOURCE_USERNAME=kyvy
      - SPRING_DATASOURCE_PASSWORD=2407
      - APP_BASE_URL=http://api-gateway:9000
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
      - EUREKA_INSTANCE_HOSTNAME=order-service
    networks:
      - cnpm-network
    depends_on:
      - mysql
      - eureka-service

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    image: tcwiuy/notification-service:latest
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/notification_db
      - SPRING_DATASOURCE_USERNAME=kyvy
      - SPRING_DATASOURCE_PASSWORD=2407
      - APP_BASE_URL=http://api-gateway:9000
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
      - EUREKA_INSTANCE_HOSTNAME=notification-service
    networks:
      - cnpm-network
    depends_on:
      - mysql
      - eureka-service
      - kafka

  # --- FRONTEND ---
  frontend:
    image: tcwiuy/food-ordering-frontend:latest
    environment:
      - REACT_APP_API_URL=http://api-gateway:9000
    ports:
      - "80:80"
    networks:
      - cnpm-network
    depends_on:
      - api-gateway

    # --- MONITORING STACK ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - cnpm-network
    depends_on:
      - api-gateway
      - user-service
      - restaurant-service
      - order-service
      - notification-service

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    ports:
      - "9093:9093"
    networks:
      - cnpm-network
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - cnpm-network
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki

  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - cnpm-network
    volumes:
      - ./monitoring/loki/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command:
      - -config.file=/etc/loki/local-config.yaml
    depends_on:
      - prometheus

  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    networks:
      - cnpm-network
    volumes:
      - ./monitoring/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki

  mysql:
    image: mysql:8.0.36
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - cnpm-network
    environment:
      MYSQL_ROOT_PASSWORD: 2407
      MYSQL_USER: kyvy
      MYSQL_PASSWORD: 2407
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  grafana-data:
  mysql-data:
  loki-data:
