eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  server:
    port: 8081
  security:
    enabled: false   # nếu Spring Boot 3, dùng security.authorization.enabled: false
