eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    preferIpAddress: false
    hostname: restaurant-service

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
